### ISSUE TITLE
使用docker镜像部署的服务, 修改网站信息不会生效

### ISSUE THREAD

**Issue by yougg** [Mereithhh/van-nav#52]
感谢作者提供优秀的开源服务, 我在尝试功能时遇到一些问题还请帮忙看看,谢谢.

<hr>

docker-compose.yaml内容如下:

```yaml
services:
  nav:
    image: mereith/van-nav:latest
    container_name: nav
    restart: always
    ports:
      - 6412:6412
    volumes:
      - ./data:/app/data
```

从1.9.x到1.10.0到1.11.x每个版本的镜像都试过了, 修改网站信息无效
提示信息为"修改成功!", 但是页面自动刷新又变回初始值了, 从控制台查看响应状态码是200
后台日志也没有任何错误信息

```
[GIN] 2024/12/17 - 17:16:16 | 200 |     689.275µs | 192.192.100.104 | PUT      "/api/admin/setting"
```

试着使用curl请求API修改信息也是相同的结果

<hr>

在1.11.x版本进入首页是空白的看不到管理入口, 如果是设计就这样建议还是右下角添加一个入口比较直观
![image](https://github.com/user-attachments/assets/0b868402-bcba-460a-ae2c-6ee1b1b57a18)

还有就是黑暗主题下几乎看不清图标
![image](https://github.com/user-attachments/assets/a1cbbf12-44f2-4843-9ba9-6fe632ebcdec)
